version: '2.3.3'
services:
  API:
    image: 'softtech_bitirme.jar'
    ports:
      - "8080:8080"
    depends_on:
      - softtech-bitirme
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://softtech-bitirme:5432/softtech-bitirme
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  softtech-bitirme:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=0000
      - POSTGRES_USER=postgres
      - POSTGRES_DB=softtech-bitirme
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5