package tr.softtech.patika.enums;

public enum CategoryEnum {
    GIDA,OFIS_KIRTASIYE,GIYECEK,
    TEKNOLOJI,TEMIZLIK,EV_YASAM,
    BAHCE,BANYO,ELEKTRIK_TESISAT,
    BEBEK,OYUNCAK,SPOR,KOZMETIK,
    PET_SHOP,KITAP,MUZIK,HOBI
}
